### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by adrianmihalko** [OutsourcedGuru/Octo-Redirect#1]
If it is possible, please consider to add a guide for Linux PC based installation of OctoPrint (as server).

**Comment by OutsourcedGuru** [comment]
To me, the reason for rfc2217 would be to separate the controlling computer from the printer (in distance). There should be some reason to have the Raspberry Pi 3B far enough away from the printer to be too far for a serial cable. I'm not completely convinced that it's at all necessary for most people, in other words.

That said, this tutorial assumes that the rfc2217 "server" is the Pi Zero (running from a basic Raspbian image which itself is a flavor of **Linux**). The rfc2217 "client" in this case is the Pi 3B (running the OctoPi image which is itself Raspbian/Linux).

I'm not a fan of using PC-based technology for things which to me are IoT. The electricity cost to run a typical PC's ATX power supply (here in California) is over $100/year versus the $5/year equivalent for a Raspi.

I tend to go with the 80%/20% rule: solve problems for 80% of the people. So no, I won't be updating the tutorial for those who want to dedicate a PC. Read the existing tutorial and make the changes required for your unique setup. Good luck.

**Comment by adrianmihalko** [comment]
Sorry, I expressed myself wrong. I wanted to use Pi Zero as server (connected to the printer) and as client (with OctoPrint running) my current server on PC. But if you are not interested in that, no problem. 👋

**Comment by OutsourcedGuru** [comment]
Start from this [Raspi3B](https://github.com/OutsourcedGuru/Octo-Redirect/blob/master/Setup.md#raspi3b) section and follow the advice there for the Linux (OctoPrint) client. It's possible that you wouldn't have to run that first script, though. It will be necessary to edit the OctoPrint code itself to allow `tcp2217:` sort of connections.
